In [1]:
import pandas as pd
import numpy as np

In [2]:
f = "../data/precipitacion/B26289.csv"
gasto = pd.read_csv(f, skiprows=7, usecols=[0, 2], index_col=0, parse_dates=[0])
gasto.columns = gasto.columns.str.strip()
gasto

           Gasto(m³/s)
Fecha
1960-06-01        2.44
1960-06-02        2.03
1960-06-03        1.78
1960-06-04        1.62
1960-06-05        1.58
...                ...
2021-06-03         NaN
2021-06-04         NaN
2021-06-05         NaN
2021-06-06         NaN
2021-06-07         NaN

[22287 rows x 1 columns]

In [3]:
gasto["Gasto(m³/s)"] = pd.to_numeric(gasto["Gasto(m³/s)"], errors="coerce")
gasto_mensual = gasto.resample("ME").mean()
gasto_mensual["year"] = gasto_mensual.index.year
gasto_mensual["month"] = gasto_mensual.index.month
gasto_mensual_pivot = gasto_mensual.pivot(index="year", columns="month", values="Gasto(m³/s)")
gasto_mensual_pivot["anual"] = gasto_mensual_pivot.mean(axis=1)
gasto_mensual_pivot.loc["medio_mensual"] = gasto_mensual_pivot.mean(numeric_only=True)
gasto_mensual_pivot.dropna(inplace=True)
gasto_mensual_pivot.to_csv("../data/precipitacion/gasto_mensual.csv")
gasto_mensual_pivot

month,1,2,3,4,5,6,7,8,9,10,11,12,anual
year,,,,,,,,,,,,,
1961,17.692903,11.572143,4.064194,2.311000,1.768387,67.359000,94.618387,91.072581,56.660000,60.543548,40.773000,10.289677,38.227068
1962,5.645161,3.791071,2.817419,22.088000,10.440645,29.723000,47.798065,8.450968,65.645667,19.260645,11.371667,12.027097,19.921617
1963,6.415484,3.629286,2.400645,1.413667,1.876129,11.245000,113.748065,47.123226,30.823667,15.236774,11.319333,6.595484,20.985563
1964,5.548710,3.223448,2.176452,5.427000,2.590968,12.645667,14.572258,2.978065,11.815333,18.507742,14.928000,28.259032,10.222723
1965,10.431290,3.616429,2.622903,7.640667,9.023226,18.698333,54.778387,124.243548,45.956333,30.819677,13.518000,4.765161,27.176163
1966,3.488065,4.292500,3.183548,3.431667,9.904194,102.906667,38.930645,38.600323,66.279667,85.580968,23.313333,7.655484,32.297255
1967,5.818387,4.694286,5.704516,2.792667,4.030323,9.228667,7.771290,60.464194,210.321667,60.235484,26.982000,8.877419,33.910075
1968,6.741613,5.660690,5.495806,6.217333,17.535484,29.089667,62.601935,46.366452,97.773000,56.595806,17.368667,21.765806,31.101022
1969,13.079677,13.185714,9.785806,7.257667,12.718710,3.018000,33.557097,73.766452,256.378333,51.557419,21.541667,13.593226,42.453314
1970,6.166452,5.808571,4.638065,2.598333,1.896452,74.279667,55.406774,39.608387,118.744333,36.644839,9.400667,4.518387,29.975911
1971,3.490323,2.863214,2.536129,14.109000,2.964839,17.540000,24.963871,51.915484,67.821667,157.934194,47.488000,11.742903,33.780802
1972,7.764839,5.903793,6.207742,2.698667,3.223548,63.266000,92.830968,66.051613,39.223667,35.720000,16.096000,7.062581,28.837451
1973,4.146774,2.795357,3.190323,1.389667,9.622258,81.108000,66.012903,149.284194,57.046333,68.878710,12.419333,13.537097,39.119246
1974,15.234839,4.708214,3.375806,4.519333,5.168065,59.545667,114.593548,22.545806,224.899000,56.409355,20.101000,12.807419,45.325671
1975,7.979032,6.754643,3.160000,1.661333,3.175806,7.933667,41.830323,99.894839,296.865333,57.627097,15.587000,8.771935,45.936751
1976,6.948710,5.176207,8.520323,3.758667,9.849355,29.618000,166.526129,123.040645,177.556667,125.038387,31.523333,18.173871,58.810858
1977,10.996129,9.753214,5.139677,3.051333,3.128710,13.541667,15.157419,14.157419,29.370333,53.411935,29.721000,10.548387,16.498102
1978,5.013871,4.850714,4.779355,4.116000,1.401290,50.096667,29.227097,80.270000,187.782333,135.126129,20.478667,10.860000,44.500177
1979,6.019032,5.121786,4.285806,4.396667,4.022581,21.880000,17.160645,73.998387,130.125000,13.489355,19.927667,15.531935,26.329905
1980,9.536774,6.563103,6.684839,6.298667,2.871290,5.462667,5.857097,41.777419,128.138667,31.288710,14.014333,9.167097,22.305055
1982,8.246774,6.456786,5.620323,16.405333,17.640323,5.855000,7.554516,4.319355,37.237667,22.490968,9.405000,8.945806,12.514821
1983,14.491290,6.311786,3.446129,2.029000,1.467097,2.124667,139.803548,67.885806,126.242333,54.441613,20.562667,11.252581,37.504876
1984,10.781613,11.989310,4.784516,2.079333,27.167742,51.368333,155.027742,65.660323,526.804000,52.816129,17.425667,6.753226,77.721495
1985,5.188710,4.168214,5.857097,14.707333,7.167742,59.311667,246.244194,80.972581,39.049000,43.767419,11.084667,5.974839,43.624455
1986,7.785484,6.426071,3.380000,1.848667,4.501935,64.446667,46.679032,14.601290,62.291333,79.937742,32.552333,14.241935,28.224374
1987,8.059355,4.636071,6.526452,3.969000,6.349032,27.836667,217.310968,84.638710,120.183000,36.873226,12.151667,6.873548,44.617308
1988,4.700645,4.686207,3.716129,18.583333,3.471935,28.037000,62.735806,66.863226,269.435667,22.152903,10.567000,5.817419,41.730606
1989,3.829677,11.311429,5.004516,2.658667,2.094194,1.990000,14.091935,70.073226,171.601667,42.809032,17.040000,22.834516,30.444905
1990,12.461290,6.997143,5.750968,8.765333,4.582903,5.650667,102.997419,96.704516,105.838333,61.206774,22.950333,22.875161,38.065070
1991,11.604194,6.110714,3.243548,3.210000,2.631613,18.907000,149.507419,25.585161,118.574667,236.731935,51.689333,18.387097,53.848557
1992,17.764194,22.574828,10.326452,13.794333,21.441935,28.793000,94.306774,94.875161,161.820667,189.785161,60.082000,14.903871,60.872365
1993,9.717097,12.488214,7.569032,7.723000,16.767742,179.965667,156.152581,77.816774,289.855667,79.997097,52.456333,12.807742,75.276412
1994,8.249032,6.510000,5.014516,3.786333,5.594516,10.667667,10.397097,42.051290,115.497000,32.071935,14.793000,13.438065,22.339204
1995,7.076129,6.570714,5.528387,3.026333,1.834194,11.119000,37.734839,95.017097,62.586000,39.374516,33.734000,15.370968,26.581015
1996,7.659355,4.508621,3.102903,2.263667,2.119032,16.815667,14.540645,67.764194,56.872667,27.814516,14.975667,6.809677,18.770551
1997,4.251935,3.551071,5.302258,15.613000,10.054839,8.602000,27.720968,10.345484,35.571333,56.568065,12.987667,6.463548,16.419347
1998,3.773548,2.836786,2.041935,1.353667,1.062258,0.910000,9.435806,28.936774,203.068000,226.105161,76.858333,21.626774,48.167420
1999,8.647097,5.078929,3.480000,2.320333,1.410323,10.712000,94.908065,25.449032,103.106000,276.318710,17.510667,9.043871,46.498752
2000,6.100323,4.753448,3.518710,4.122667,5.119677,68.630667,19.804516,70.741613,45.542000,53.734194,15.603333,20.513548,26.515391
2001,7.374194,7.376429,4.388387,2.800667,6.847419,8.881333,33.551613,27.211935,141.549000,36.812258,21.482000,8.731290,25.583877
2002,4.790645,3.230357,2.209032,1.499667,1.508387,15.717667,38.731613,14.023226,83.003000,43.332258,41.371667,10.671935,21.674121
2003,11.148065,12.328214,5.593871,3.319333,1.402903,4.840333,15.238710,42.286774,199.832667,90.724516,51.834333,12.251935,37.566805
2004,6.934516,4.755172,7.398387,11.392000,26.908710,56.260000,26.343226,39.318710,41.153000,58.584516,11.802000,5.952581,24.733568
2005,4.614516,4.460357,3.368710,2.102667,5.034839,10.106667,33.039677,130.930968,74.279667,171.027742,28.373333,12.610323,39.995789
2006,6.533226,4.634286,3.459032,1.830667,2.268710,6.102000,13.190968,30.260968,65.950667,73.940645,39.158000,32.152903,23.290173
2007,10.485161,29.055357,8.663871,6.219000,2.325484,6.250000,6.616129,94.997419,168.249000,87.502903,21.299000,16.568065,38.185949
2008,11.450000,7.270345,3.376129,2.889333,2.727742,40.419333,150.053548,45.595161,162.497000,117.046452,30.082000,11.815484,48.768544
2009,5.456774,7.325357,4.189677,2.569333,1.914839,4.817000,17.855484,7.540000,134.002667,112.430968,26.241333,18.385806,28.560770
2010,17.635484,27.914643,9.104516,10.224000,4.586774,4.434667,180.437097,115.032903,197.614333,27.195806,10.144000,5.973871,50.858175
2011,4.528710,4.074286,3.388065,1.359000,2.771935,11.456333,94.789677,9.659355,13.450333,6.578710,6.289333,6.123548,13.705774
2012,16.130323,17.440000,11.296129,9.923667,8.234839,10.938667,26.366452,114.757097,24.301667,16.632903,13.777667,10.993871,23.399440
2013,12.668387,11.917857,10.632903,9.145667,12.864839,35.629667,39.734839,49.083226,195.133667,42.256452,87.662667,23.351290,44.173455
2014,19.193226,14.465000,13.479677,13.353000,15.443226,61.452333,48.098065,19.486452,79.108333,133.914516,29.388667,18.253226,38.802977
medio_mensual,8.631869,7.701479,5.179842,5.925748,6.689282,29.423247,64.197473,57.629731,122.209858,71.508835,25.592549,13.054241,35.027251

In [4]:
gasto_diseno = pd.DataFrame(gasto_mensual_pivot["anual"].sort_values(ascending=False))
gasto_diseno.index = np.arange(1, len(gasto_diseno) + 1)
gasto_diseno.columns = ["Gasto(m³/s)"]
gasto_diseno["Tr"] = (len(gasto_diseno) + 1) / gasto_diseno.index
gasto_diseno["Pe"] = 1 / gasto_diseno["Tr"]
gasto_diseno

    Gasto(m³/s)         Tr        Pe
1     77.721495  55.000000  0.018182
2     75.276412  27.500000  0.036364
3     60.872365  18.333333  0.054545
4     58.810858  13.750000  0.072727
5     53.848557  11.000000  0.090909
6     50.858175   9.166667  0.109091
7     48.768544   7.857143  0.127273
8     48.167420   6.875000  0.145455
9     46.498752   6.111111  0.163636
10    45.936751   5.500000  0.181818
11    45.325671   5.000000  0.200000
12    44.617308   4.583333  0.218182
13    44.500177   4.230769  0.236364
14    44.173455   3.928571  0.254545
15    43.624455   3.666667  0.272727
16    42.453314   3.437500  0.290909
17    41.730606   3.235294  0.309091
18    39.995789   3.055556  0.327273
19    39.119246   2.894737  0.345455
20    38.802977   2.750000  0.363636
21    38.227068   2.619048  0.381818
22    38.185949   2.500000  0.400000
23    38.065070   2.391304  0.418182
24    37.566805   2.291667  0.436364
25    37.504876   2.200000  0.454545
26    35.027251   2.115385  0.472727
27    33.910075   2.037037  0.490909
28    33.780802   1.964286  0.509091
29    32.297255   1.896552  0.527273
30    31.101022   1.833333  0.545455
31    30.444905   1.774194  0.563636
32    29.975911   1.718750  0.581818
33    28.837451   1.666667  0.600000
34    28.560770   1.617647  0.618182
35    28.224374   1.571429  0.636364
36    27.176163   1.527778  0.654545
37    26.581015   1.486486  0.672727
38    26.515391   1.447368  0.690909
39    26.329905   1.410256  0.709091
40    25.583877   1.375000  0.727273
41    24.733568   1.341463  0.745455
42    23.399440   1.309524  0.763636
43    23.290173   1.279070  0.781818
44    22.339204   1.250000  0.800000
45    22.305055   1.222222  0.818182
46    21.674121   1.195652  0.836364
47    20.985563   1.170213  0.854545
48    19.921617   1.145833  0.872727
49    18.770551   1.122449  0.890909
50    16.498102   1.100000  0.909091
51    16.419347   1.078431  0.927273
52    13.705774   1.057692  0.945455
53    12.514821   1.037736  0.963636
54    10.222723   1.018519  0.981818

In [5]:
(gasto_diseno.loc[49,"Gasto(m³/s)"] - gasto_diseno.loc[48,"Gasto(m³/s)"]) * (0.85 - gasto_diseno.loc[48,"Pe"]) / (gasto_diseno.loc[49,"Pe"] - gasto_diseno.loc[48,"Pe"]) + gasto_diseno.loc[48,"Gasto(m³/s)"]

np.float64(21.36044985775642)

In [6]:
volumen = gasto * 3600 * 24
volumen.columns = ["Volumen(m³/día)"]
volumen["Volumen(m³/día)"] = pd.to_numeric(volumen["Volumen(m³/día)"], errors="coerce")
volumen_mensual = volumen.resample("ME").sum()
volumen_mensual.columns = ["Volumen (m³/mes)"]
volumen_mensual["year"] = volumen_mensual.index.year
volumen_mensual["month"] = volumen_mensual.index.month
volumen_mensual_pivot = volumen_mensual.pivot(index="year", columns="month", values="Volumen (m³/mes)") 
volumen_mensual_pivot["anual"] = volumen_mensual_pivot.sum(axis=1)
volumen_mensual_pivot.loc["medio_mensual"] = volumen_mensual_pivot.mean(numeric_only=True)
volumen_mensual_pivot.dropna(inplace=True)
volumen_mensual_pivot = volumen_mensual_pivot[(volumen_mensual_pivot != 0).all(axis=1)]
volumen_mensual_pivot.to_csv("../data/precipitacion/volumen_mensual.csv")

In [7]:
Q = (gasto_diseno.loc[49,"Gasto(m³/s)"] - gasto_diseno.loc[48,"Gasto(m³/s)"]) * (0.85 - gasto_diseno.loc[48,"Pe"]) / (gasto_diseno.loc[49,"Pe"] - gasto_diseno.loc[48,"Pe"]) + gasto_diseno.loc[48,"Gasto(m³/s)"]

In [10]:
cargas = [
    [1,Q,1000,0.85,9.81],
    [1,Q/2,1000,0.85,9.81],
    [2,Q,1000,0.85,9.81],
    [2,Q/2,1000,0.85,9.81],
    [3,Q,1000,0.85,9.81],
    [3,Q/2,1000,0.85,9.81],
    [4,Q,1000,0.85,9.81],
    [4,Q/2,1000,0.85,9.81],
    [5,Q,1000,0.85,9.81],
    [5,Q/2,1000,0.85,9.81],
    [10,Q,1000,0.85,9.81],
    [10,Q/2,1000,0.85,9.81],
]

In [12]:
Hb = pd.DataFrame(cargas, columns=["P","Q","gamma","Eta","g"])
Hb

     P          Q  gamma   Eta     g
0    1  21.360450   1000  0.85  9.81
1    1  10.680225   1000  0.85  9.81
2    2  21.360450   1000  0.85  9.81
3    2  10.680225   1000  0.85  9.81
4    3  21.360450   1000  0.85  9.81
5    3  10.680225   1000  0.85  9.81
6    4  21.360450   1000  0.85  9.81
7    4  10.680225   1000  0.85  9.81
8    5  21.360450   1000  0.85  9.81
9    5  10.680225   1000  0.85  9.81
10  10  21.360450   1000  0.85  9.81
11  10  10.680225   1000  0.85  9.81

In [15]:
Hb["Hb"] = Hb["P"] * 1e6 / (Hb["gamma"] * Hb["Q"] * Hb["Eta"] * Hb["g"])
Hb

     P          Q  gamma   Eta     g          Hb
0    1  21.360450   1000  0.85  9.81    5.614378
1    1  10.680225   1000  0.85  9.81   11.228757
2    2  21.360450   1000  0.85  9.81   11.228757
3    2  10.680225   1000  0.85  9.81   22.457513
4    3  21.360450   1000  0.85  9.81   16.843135
5    3  10.680225   1000  0.85  9.81   33.686270
6    4  21.360450   1000  0.85  9.81   22.457513
7    4  10.680225   1000  0.85  9.81   44.915026
8    5  21.360450   1000  0.85  9.81   28.071891
9    5  10.680225   1000  0.85  9.81   56.143783
10  10  21.360450   1000  0.85  9.81   56.143783
11  10  10.680225   1000  0.85  9.81  112.287566